house <- read.csv("household_power_consumption.txt",sep=";",header=TRUE, stringsAsFactors=FALSE,dec=".")
two_data <- subset(house,(Date %in% c("1/2/2007","2/2/2007")))
s_act_1 <- as.numeric(two_data$Global_active_power)
merge_time <- paste(two_data$Date,two_data$Time)
strp_time <- strptime(merge_time,"%d/%m/%Y %H:%M:%S")
png("plot2.png",width=480,height=480)
plot(strp_time,s_act_1,type="l",xlab="",ylab="Global Active Power(Kilowatts)")
dev.off()
